name: 💡 Feature Request
description: Suggest an idea or improvement for the ELRS Mobile app.
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Note:** This form is for app features only. If you are requesting support for new ELRS hardware targets, please contact the official ExpressLRS team.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I find it difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the desired solution
      description: What would you like to see happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any workarounds you use now?
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which area of the app does this feature belong to?
      options:
        - UI/UX Design
        - Firmware Manager
        - Connectivity/mDNS
        - Configurator/PWM Settings
        - Other
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Please include any mockups or screenshots that help visualize your idea.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      options:
        - label: I understand that hardware target support is handled by the core ELRS project and not this app.
          required: true
        - label: I have checked existing issues to see if this feature has already been requested.
          required: true
